# Home Assistant integration (MQTT discovery)
homeassistant: false
frontend:
  port: 9442

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: "mqtt://<mqtt_broker>:1883"
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of zigbee USB
  port: /dev/ttyACM0
