#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo '
╔════════════════════════════════════════════════════╗
╠════════════════════════════════════════════════════╣
║                                                    ║
║             This image is deprecated.              ║
║      We will not offer support for this image      ║
║            and it will not be updated.             ║
║                                                    ║
╠════════════════════════════════════════════════════╣
╚════════════════════════════════════════════════════╝

No longer use this image, use `ghcr.io/koenkk/zigbee2mqtt` (should pretty much be inplace update, just set `ZIGBEE2MQTT_DATA=/config`)


══════════════════════════════════════════════════════'
