#!/usr/bin/with-contenv bash

mkdir -p \
	/config/mosquitto

[[ ! -f /config/mosquitto/mosquitto.conf ]] &&
	cp /defaults/mosquitto.conf /config/mosquitto/mosquitto.conf

# permissions
chown -R abc:abc \
	/config/mosquitto
