#!/usr/bin/with-contenv bash

if [ ! -f /config/configuration.yaml ]; then
    cp /defaults/zigbee2mqtt.yaml /config/configuration.yaml
    echo "Please modify /config/configuration.yaml to your needs and restart the container"
    sleep infinity
fi

# permissions
chown -R abc:abc \
    /config/
